---
- hosts: web
  vars:
          my_contacts : this is my variable section
  tasks: 
    - copy:
       dest: /home/ubuntu/samp.txt
       content: "{{my_contacts}}" 

- hosts:  web
  tasks:
          - command: cat /home/ubuntu/samp.txt
